language: rust
rust:
  - stable
  - beta
  - nightly

before_script:
  - |
    if [ $ACTION == "clippy" ]
    then
      rustup component add clippy-preview --toolchain=nightly
    fi

env:
  - TEST_DIR="uavcan" ACTION="test" FLAGS="--no-default-features"
  - TEST_DIR="uavcan" ACTION="test" FLAGS=""
  - TEST_DIR="dsdl_parser" ACTION="test" FLAGS=" -- --nocapture"
  - TEST_DIR="dsdl_compiler" ACTION="test" FLAGS=""
  - TEST_DIR="dsdl" ACTION="test" FLAGS=""

matrix:
  include:
    - rust: nightly
      env: TEST_DIR="uavcan" ACTION="clippy"
  
script: cd $TEST_DIR && ./travis.sh
